default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sotify_development


production:
  adapter: mysql2
  database: cav7lul1v4ohx075
